# 1. 수학과 파이썬

In [3]:
import numpy as  np

x = np.array([1,2,3])
x.__class__ # 클래스 이름 표시

numpy.ndarray

In [4]:
# 다차원 배열 형상
x.shape

(3,)

In [5]:
# 차원수
x.ndim

1

x 는 1차원 배열, 원소수는 3개

In [7]:
W = np.array([[1,2,3],[4,5,6]])
W

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
W.shape

(2, 3)

In [9]:
W.ndim

2

W는 2차원 배열, 2x3(2행3열) 행렬

In [20]:
# 행렬 원소별 연산
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
print("W+X:",W+X)
print("W*X:",W*X)

W+X: [[ 1  3  5]
 [ 7  9 11]]
W*X: [[ 0  2  6]
 [12 20 30]]


In [21]:
# 브로드캐스트
A = np.array([[1,2],[3,4]])
A*10

array([[10, 20],
       [30, 40]])

In [22]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])
A*b

array([[10, 40],
       [30, 80]])

In [23]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b) #1*4+2*5+3*6

32

In [24]:
# 행렬의 곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [25]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

# 2. 신경망의 추론

미니배치로 완전연결계층에 의한 변환

In [30]:
# 하나의 샘플 데이터 일때 - 미니배치 X
import numpy as np

W1 = np.random.randn(2,4) #가중치
b1 = np.random.randn(4) #편향
x = np.random.randn(10,2) #입력 배치 10개씩 2개
h = np.matmul(x,W1) + b1

In [31]:
x   # x[0]은 첫번째 입력 데이터, x[1]은 두번째 입력 데이터

array([[ 0.41360437, -2.31678672]])

In [32]:
h

array([[-3.20108354, -1.38448645,  1.65956746, -2.9809838 ]])

In [33]:
W1

array([[ 0.01333976, -0.6259804 ,  0.37095288, -2.23130077],
       [ 0.33625674,  0.24738976, -0.94479458,  1.10943606]])

In [38]:
# 10개의 샘플 데이터 - 미니배치 
import numpy as np

W1 = np.random.randn(2,4) #가중치
b1 = np.random.randn(4) #편향
x = np.random.randn(10,2) #입력 배치 10개씩 2개
h = np.matmul(x,W1) + b1

In [39]:
x   # x[0]은 첫번째 입력 데이터, x[1]은 두번째 입력 데이터

array([[-9.88096407e-01, -1.55195157e+00],
       [-2.61915434e-01,  5.05205729e-04],
       [ 1.53541833e-01,  1.19578213e-01],
       [-5.88386560e-01, -3.60860653e-01],
       [-5.23657245e-01, -3.56391539e-01],
       [ 1.40312693e+00, -2.26021915e-01],
       [-1.44105659e+00, -1.68453011e+00],
       [-5.59082129e-01, -3.48824285e-02],
       [-1.71256267e-01, -3.94940715e-01],
       [-2.89320946e-01,  8.03973201e-01]])

In [40]:
h

array([[ 0.53650578,  0.96068651,  3.58961802,  4.87968841],
       [-0.24061606, -1.29398949,  2.17597131, -0.59371071],
       [-0.64640737, -1.88038916,  1.64939786, -1.72091971],
       [ 0.09177273, -0.58822674,  2.68801567,  0.98990659],
       [ 0.02926002, -0.66670733,  2.61114125,  0.85098235],
       [-1.83140845, -3.00038821,  0.32381278, -3.27741112],
       [ 0.97906659,  1.60254175,  4.16473627,  6.11583364],
       [ 0.04712473, -0.92008949,  2.53435117,  0.08282856],
       [-0.30790024, -1.03645479,  2.21569078,  0.25850457],
       [-0.25478827, -1.99745267,  1.91302571, -2.63355438]])

In [41]:
W1

array([[-0.96227171, -1.14928662, -1.16229665, -1.96631645],
       [-0.05046095, -0.91473459, -0.36690812, -2.60586806]])

In [3]:
# 전체 코드 종합 정리
import numpy as np

# sigmoid 함수
def sigmoid(x):
    return 1/(1+np.exp(-x))

# 입력,가중치,편향
x = np.random.randn(10,2)  # 2차원 데이터 10개가 미니배치로 처리된다.
W1 = np.random.randn(2,4)  # (10,2) * (2,4) = (10,4)  은닉층 뉴련 4개
b1 = np.random.randn(4)

h = np.matmul(x,W1) + b1 # 은닉층 출력 (10,4)
a = sigmoid(h)

W2 = np.random.randn(4,3) # (10,4) * (4,3) = (10,3) 최종 출력은 3이다.
b2 = np.random.randn(3)

s = np.matmul(a,W2) + b2 # 최종 출력 (10,3) : 3차원 데이터 10개가 한번에 처리되어 변환되었다.
                        # 3차원 데이터 : 각 차원의 값을 이용하여 3 클래스 분류가 된다.
                        # 출력된 3차원 벡터의 각 차원은 각 클래스에 대응하는 점수이다. 

In [4]:
x 

array([[-0.23103062,  1.64480411],
       [ 1.04448933, -0.96611174],
       [-0.85959121,  0.21105908],
       [-0.88079755, -0.9679427 ],
       [ 0.4407228 , -0.98630427],
       [-0.99067592,  0.32500561],
       [ 0.21036924, -0.63649026],
       [ 0.21758813, -1.04857776],
       [-0.21754266,  0.5780632 ],
       [ 1.11392173,  0.53190679]])

In [5]:
print(x.shape)
print(h.shape)
print(s.shape)

(10, 2)
(10, 4)
(10, 3)


# 계층 클래스화 - 신경망 추론(forward())
Affine 계층, Sigmoid 계층, forward() 

In [14]:
import numpy as np

# 시그모이드 함수 클래스 구현
class Sigmoid:
    def __init__(self):
        self.params = []     # sigmoid는 학습할 매개변수가 없음 = 빈 리스트 
    
    def forward(self,x):
        return 1 / (1+np.exp(-x))
    
# Affine 계층 클래스 구현
class Affine:
    def __init__(self,W,b):
        self.params = [W,b]  # 초기화될 때 Aiffine 계층의 매개변수 (가중치,편향)을 받는다. 
                            # 신경망 학습 시 수시로 갱신됨
        
    def forward(self,x):
        W,b = self.params
        out = np.matmul(x,W) + b
        return out

학습해야 하는 매개변수가 모두 인스턴스 변수이 params에 존재한다. 이 덕분에 신경망의 모든 매개변수를 간단하게 사용가능하다.

![image](https://user-images.githubusercontent.com/77032087/130582430-68a4ac90-dcf6-4e80-84bf-b96100477d01.png)

입력 X 가 Affine 계층→Sigmoid 계층→Affine 계층을 거쳐 점수 S로 출력된다.

이러한 신경망을 TwoLayerNet이라는 클래스로 추상화하고, 주요한 추론 처리는 predict(x) 메서드이다.

In [17]:
class TwoLayerNet:
    def __init__(self,input_size,hidden_size,output_size):
        I,H,O = input_size,hidden_size,output_size
        
        # 가중치와 편향 초기화
        W1 = np.random.randn(I,H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H,O)
        b2 = np.random.randn(O)
        
        # 3개 계층 생성
        self.layers = [
            Affine(W1,b1),
            Sigmoid(),
            Affine(W2,b2)
        ]
        
        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layers in self.layers:
            self.params += layers.params # 각 계층은 필요한 매개변수를 인스턴스 변수 params로 보관하고 있음
        
        # TwoLayerNet의 params 변수에는 필요한 모든 학습 매개변수가 담겼다.
        
    def predict(self,x):
        for layers in self.layers:
            x = layers.forward(x)
            
        return x

In [18]:
# 입력데이터 X에 대한 출력 점수 S 를 구할 수 있다.
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)

In [19]:
x

array([[ 3.04574517e-02,  1.16679601e-01],
       [ 3.93822877e-01,  1.25041689e+00],
       [-1.83294443e+00, -1.91999650e+00],
       [-1.50849984e+00,  1.63230535e+00],
       [-1.36844526e+00,  8.95303137e-01],
       [-5.66293096e-02, -1.45457793e+00],
       [ 1.01534960e+00,  6.53730848e-04],
       [-6.39901597e-02, -5.54455566e-01],
       [-3.27376363e-01, -3.23634314e-01],
       [ 1.60667430e+00, -9.92828777e-01]])

In [20]:
s

array([[ 1.49814974,  1.19450326, -3.0715319 ],
       [ 2.37242636,  1.01547527, -2.3974578 ],
       [-0.49021312,  2.58941221, -4.12396683],
       [ 1.24633056,  2.26168815, -2.50806617],
       [ 1.08779988,  2.27590244, -2.55495388],
       [ 0.60030268,  1.13258232, -3.40351503],
       [ 1.89709211,  0.33853062, -2.99775334],
       [ 1.02216424,  1.21609753, -3.37403232],
       [ 1.00112524,  1.50325833, -3.31921416],
       [ 1.91222394,  0.03545938, -2.90021788]])

## 손실함수 - 소프트맥스/교차 엔트로피 오차

In [ ]:
class SoftmaxWithLoss:
    def __init__(self):
        self.params, self.grads = [], []
        self.y = None  # softmax의 출력
        self.t = None  # 정답 레이블

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)

        # 정답 레이블이 원핫 벡터일 경우 정답의 인덱스로 변환
        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)

        loss = cross_entropy_error(self.y, self.t)
        return loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]

        dx = self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx *= dout
        dx = dx / batch_size

        return dx